### ISSUE TITLE
Best Kernel Error

### ISSUE THREAD

**Issue by vinecodes** [luca020400/dotfiles#1]
It gets stuck and doesn't show anything after this.

```
kernel$ ./best_kernel -j4 *-8x16.0
number of tags to check: 883
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./best_kernel", line 71, in background
    print("%s has %d lines changed" % (tn, tc))
TypeError: %d format: a number is required, not NoneType
```

**Comment by vinecodes** [comment]
For people using best_kernel, to fix this problem

-> commit the changes in the tree

-> then run the script. Example: best_kernel -j10 "LA.BR.*"

**Comment by JerryCheng1** [comment]
$ git add --all
$ git commit -m "add best_kernel"
[master 5c30898b] add best_kernel
 1 file changed, 116 insertions(+)
 create mode 100755 best_kernel
$ ./best_kernel -j8 "*-8x94.0"
number of tags to check: 1
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "./best_kernel", line 71, in background
    print("%s has %d lines changed" % (tn, tc))
TypeError: %d format: a number is required, not NoneType
$

still doesn't show.

**Comment by vinecodes** [comment]
You didn't fetch the CAF tags into your repo.

**Comment by vinecodes** [comment]
This is how you do it:

```
git add . && git commit -m "<commit message>"
git remote add caf https://source.codeaurora.org/quic/la/kernel/msm-3.18/
git fetch --all
./best_kernel -j10 "LA.BR.*"
```

Output will be something like this:

> number of tags to check: 1132
........
........
........
> LA.BR.1.3.7-05010-8976.0 has 9174388 lines changed
> LA.BR.1.3.5-03110-8976.0 has 9158083 lines changed
> LA.BR.1.3.3-05510-8952.0 has 9217299 lines changed
> LA.BR.1.3.3.c5-00700-8976.0 has 9217676 lines changed
> LA.BR.1.LA.BR.1.1.3.c4-02900-8x16.0 has 9511903 lines changed
> LA.BR.5.6-00500-89xx.0 has 1352202 lines changed
> LA.BR.5.6-00500-89xx.0 is the new best match with 1352202 lines changed
> LA.BR.1.3.5-03310-8976.0 has 9157987 lines changed
> LA.BR.1.3.3-05530-8976.0 has 9229698 lines changed
> LA.BR.1.3.3.c5-00800-8976.0 has 9217680 lines changed
> LA.BR.1.3.5-03610-8976.0 has 9156782 lines changed
> LA.BR.1.3.3-05620-8976.0 has 9211935 lines changed
> LA.BR.1.3.3.c5-01200-8976.0 has 9216048 lines changed
> LA.BR.1.3.5-03810-8976.0 has 9157352 lines changed
> LA.BR.1.3.3-05710-8952.0 has 9215580 lines changed
> LA.BR.1.3.3.c5-01300-8976.0 has 9216047 lines changed
> LA.BR.1.3.5-04110-8976.0 has 9157482 lines changed
> LA.BR.1.3.3-05720-8976.0 has 9211249 lines changed
> LA.BR.1.3.3.c5-01400-8976.0 has 9216049 lines changed
> LA.BR.1.3.5-05000-8976.0 has 9188833 lines changed
> Best match
> TAG: LA.BR.5.6-00500-89xx.0
> Lines changed: 1352202
